MyWebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^web0/', include('web0.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)	
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)	

web0/urls.py
from django.conf.urls import url
from . import views

app_name = "web0"
urlpatterns = [
	# /web0/
    url(r'^$', views.IndexView.as_view(), name = 'index'),

    #/web0/register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /web0/<album_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /web0/<album_id>/addsong
    url(r'^(?P<album_id>[0-9]+)/addsong/$', views.AddSong, name='song-add'),

    # /web0/<album_id>/addedsong
    url(r'^(?P<album_id>[0-9]+)/addedsong/$', views.AddedSong, name='song-added'),

    # /web0/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    #/web0/album/<album_id>/
    url(r'album/(?P<album_id>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    #/web0/album/<album_id>/delete
    url(r'album/(?P<album_id>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
]

web0/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length = 255)	
	album_title = models.CharField(max_length = 255)
	genre = models.CharField(max_length = 255)
	album_logo = models.FileField()

	def get_absolute_url(self):
		return reverse('web0:detail', kwargs={'pk':self.pk})
	def __str__(self):
		return self.album_title + ' - ' + self.artist

class  Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length = 10)	
	song_title = models.CharField(max_length = 255)	
	song_src = models.FileField()
	is_favorite = models.BooleanField(default = False)
	def __str__(self):
		return self.song_title
					

web0/forms.py
from django import forms
from web0.models import Album, Song
from django.contrib.auth.models import User 

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['file_type', 'song_title', 'song_src']
        widgets = {"user": forms.HiddenInput()}

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username', 'email', 'password']

web0/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, Http404
from .models import Album, Song
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from web0.forms import SongForm, UserForm

# Create your views here.

class IndexView(generic.ListView):
	template_name = 'web0/index.html'
	context_object_name = 'all_albums'
	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = "web0/detail.html"

class  AlbumCreate(CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class  AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']
	pk_url_kwarg = "album_id"

class AlbumDelete(DeleteView):
	model = Album
	pk_url_kwarg = "album_id"
	success_url = reverse_lazy('web0:index')	

def AddSong(request, album_id):
	form = SongForm()
	album = get_object_or_404(Album, pk=album_id)
	return render(request, 'web0/song_form.html', {'form': form, 'album': album})

def AddedSong(request, album_id):
	a = Song()
	a.album = get_object_or_404(Album, pk=album_id)
	a.file_type = request.POST['file_type']
	a.song_title = request.POST['song_title']
	a.song_src = request.FILES['song_src']
	if not a.album.song_set.all():
		favorited = False
	else:
		for song in a.album.song_set.all():
			if song.is_favorite:
				favorited = True
			else:
				favorited = False
	if not favorited:
		a.is_favorite = True
	a.save()
	return render(request, 'web0/song_added.html')

class UserFormView(generic.View):
	form_class = UserForm
	template_name = 'web0/registration_form.html'

	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	def post(self, request):	
		form = self.form_class(request.POST)	
		if form.is_valid():
			user = form.save(commit=False)
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#returns user object if credentials are correct
			user = authenticate(username = username, password = password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('web0:index')
		else:
			return render(request, self.template_name, {'form': form})


		

web0/templates/web0/album_form.html
{%extends 'web0/base.html' %}
{% block title %}Add new album{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="panel panel-default">
			<div class="panel-body">
				<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{%include 'web0/form-template.html'%}
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

web0/templates/web0/base.html
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
	{% block title%} 
	MusicApp 
	{% endblock %}
	</title>
	<link rel="icon" type="image/icon" href="{% static 'web0/images/websiteIcon.ico' %}">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" type="text/css">
	<link rel="stylesheet" type="text/css" href="{%static 'web0/style.css'%}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
		<!-- Header -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'web0:index'%}">
				MusicApp
				</a>
			</div>
		<!-- Itens -->
			<div class="collapse navbar-collapse" id="topNavBar">

				<ul class="nav navbar-nav">
					<li class="active">
						<a href="{% url 'web0:index' %}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span> Albums
						</a>
					</li>
					<li class="#">
						<a href="#">
						<span class="glyphicon glyphicon-music" aria-hidden="true"></span> Songs
						</a>
					</li>
				</ul>

				<form class="navbar-form navbar-left" role="search" method="get" action="#">
					<div class="form-group">
						<input class="form-control" type="text" name="q" value="">
					</div>
					<button type="submit" class="btn btn-default">Search</button>
				</form>

				<ul class="nav navbar-nav navbar-right">
					<li class="#">
						<a href="{% url 'web0:album-add' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Album
						</a>
					</li>
					<li class="#">
						<a href="#">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout
						</a>
					</li>
				</ul>
				
			</div>
		</div>
	</nav>

	{%block body%}
	{%endblock%}
</body>
</html>

web0/templates/web0/detail.html
{% extends 'web0/base.html' %}
{% block title %}
	{{album}}
{% endblock %}

{% block body %}
	<div>
		<img src="{{album.album_logo.url}}" width="10%" />
		<h1>{{album}}</h1>
	</div>
	{%for song in album.song_set.all%}
		{%if song.is_favorite %}
			<audio autoplay="autoplay" loop="loop">
				<source src="{{song.song_src.url}}" type="audio/{{song.file_type}}" />
			</audio>
			<h3>
				The song playing is {{song}}
			</h3>
		{%endif%}
	{%endfor%}

	{% for song in album.song_set.all %}
			{{song.song_title}}
			{%if song.is_favorite%}
				<img src="http://i.imgur.com/b9b13Rd.png">
			{%endif%}
			<br>
	{%endfor%}

	<a href="{% url 'web0:song-add' album.id %}" class="btn btn-default btn-sm">
		Add song
	</a>

{% endblock %}

web0/templates/web0/form-template.html
{%for field in form%}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{field.error}}</span>
		</div>
		<label class="control-label col-sm-2">{{field.label_tag}}</label>
		<div class="col-sm-10">{{field}}</div>
	</div>
{%endfor%}

web0/templates/web0/index.html
{% extends 'web0/base.html' %}

{% block body %}
	{% if all_albums %}
		<h3>Here are all my albums</h3>
		<ul>
			{% for album in all_albums%}
				<li>
					<a href="{% url 'web0:detail' album.id %}"> {{album.album_title}} - {{album.artist}} </a>
					<a href="{% url 'web0:album-update' album.id %}" class="btn btn-default btn-sm"> 
					Update 
					</a>
					<form action="{% url 'web0:album-delete' album.id %}" method="post" style="display: inline;">
						{% csrf_token %}
						<input type="hidden" name="album_id" value="{{album.id}}">
						<button type="submit" class="btn btn-default btn-sm">
							<span class="glyphicon glyphicon-trash"></span>
						</button>
					</form>
				</li>
			{% endfor %}
		</ul>
		{% else %}
		<h3>You don't have any albums</h3>
	{% endif %}
{% endblock%}

web0/templates/web0/registration_form.html
{%extends 'web0/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="panel panel-default">
			<div class="panel-body">
				<p class="text-center">
					Register User
				</p>
				<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{%include 'web0/form-template.html'%}
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

web0/templates/web0/song_added.html
{%extends 'web0/base.html' %}
{% block title %}Add new album{% endblock %}

{% block body %}
	<h1 class="text-center">
		Song has been successfully added
	</h1>
{% endblock %}

web0/templates/web0/song_form.html
{%extends 'web0/base.html' %}
{% block title %}Add new album{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="panel panel-default">
			<div class="panel-body">
				<form class="form-horizontal" action="{% url 'web0:song-added' album.id %}" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{%include 'web0/form-template.html'%}
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}